version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.18.3
    environment:
      NODE_ENV: ci
      MONGO_URI: $MONGO_URI
    steps:
      - checkout
      - run: node --version
      # - run: npm install
      # - run: npm install --prefix client
      # - run: npm run test:client
      - run: npm run scripts:env

workflows:
  build:
    jobs:
      - build:
          context: trademebooks-web
