version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.18.2
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm install -D jest
      - run: npm run test:ci